line-length = 100
target-version = "py38" # default value

[format]
indent-style = "space" # default value

[lint]
# Enable Pyflakes (`F`), isort (`I`) and a subset of the pycodestyle (`E`) codes.
select = ["E4", "E7", "E9", "F", "I"]

[lint.pycodestyle]
max-line-length = 100
