#!/usr/bin/env python3

import sys

from libkcov import cobertura

if len(sys.argv) < 4:
    print("Usage: lookup-class-line <in-file> <filename> <lineNr>")
    sys.exit(1)

fileName = sys.argv[2]
line = int(sys.argv[3])

data = cobertura.readFile(sys.argv[1])

dom = cobertura.parse(data)
fileTag = cobertura.lookupClassName(dom, fileName)

if fileTag is not None:
    hits = cobertura.lookupHitsByLine(fileTag, line)
    if hits is not None:
        print(hits)
        sys.exit(0)

print("nocode")
