#!/usr/bin/env python

import sys
import unittest
import testbase

# The actual tests
from basic import *
if sys.platform.startswith("linux"):
    from compiled import *
from filter import *
from accumulate import *
from python import *
from bash import *

if __name__ == "__main__":
    testbase.configure(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])

    sys.argv = sys.argv[4:]

    unittest.main()
