#!/usr/bin/env python3

import sys
import unittest
import testbase
import platform

# The actual tests
from basic import *
from compiled import *
if sys.platform.startswith("linux"):
    from bash_linux_only import *
    if platform.machine() in ["x86_64", "i386", "i686"]:
        from system_mode import *
from filter import *
from accumulate import *
from python import *
from bash import *

if __name__ == "__main__":
    if len(sys.argv) < 5:
        print("Usage: run-tests <path-to-kcov-binary> <kcov-output> <path-to-test-builds> <path-to-kcov-source>")
        sys.exit(1)

    testbase.configure(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])

    sys.argv = sys.argv[4:]

    unittest.main()
