.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KCOV 1 "November  24, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
kcov \- Code coverage analysis using DWARF debugging information
.SH SYNOPSIS
.B kcov
.RI [ options ] " outdir executable [ args for executable ]
.SH DESCRIPTION
This manual page documents briefly the
.B kcov
command. \fBkcov\fP is a code coverage tester based on bcov by Thomas Neumann. It allows collecting code coverage information from executables without special command-line arguments, and continuously produces output from long-running applications.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invoke bold face and italics,
.\" respectively.
.SH OPTIONS
.B \-p PID, \-\-pid=PID
trace PID instead of executing executable, executable is optional in this case
.TP
.B \-s sort-type, \-\-sort-type=type
How to sort files: f[ilename] (default), p[ercent].
.TP
.B \-l low,high, \-\-limits=low,high
Setup limits for low/high coverage (default 16,50).
.TP
.B \-t title \-\-title=title
Set the web page title to title
.TP
.B \-\-path-strip-level=N
number of path levels to show for common paths (default: 2)
.TP
.B \-\-include-path=P1[,P2...]
Comma-separated list of paths to include in the report.
.TP
.B \-\-exclude-path=P1[,P2...]
Comma-separated list of paths to exclude from the report.
.TP
.B \-\-include-pattern=P1[,P2...]
Comma-separated list of patterns to include in the report.
.TP
.B \-\-exclude-pattern=P1[,P2...]
Comma-separated list of patterns to exclude from the report.
.PP
.SH EXAMPLES
Check coverage for ./frodo and generate HTML output in /tmp/kcov
.TP
.B kcov /tmp/kcov ./frodo
.TP
Check coverage for ./frodo but only include source files names with the string src/frodo
.TP
.B kcov --include-pattern=src/frodo /tmp/kcov ./frodo
.PP
.SH HTML OUTPUT
.TP
The HTML output shows executed and non-executed lines of the source code. Some lines can map to multiple instrumentation points, for example for inlined functions (where every inlining of them will generate a separate instrumentation point). This is shown in the left column as 1/3 for example, which means that one of the three instrumentation points has been executed.

.SH AUTHOR
Kcov was written by Simon Kagstrom, building upon bcov by Thomas Neumann.
.PP
This manual page was written by Michael Tautschnig <mt@debian.org>,
for the Debian project (but may be used by others).
