name: Release
on:
  release:
    types: [published]

jobs:
  build:
    name: Build executable
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]

    steps:
      - uses: actions/checkout@v2

#      - name: Prepare
#        run: chmod u+x .github/workflows/generic-build.sh .github/workflows/ci-run-tests.sh
#
#      - name: Build for matrix.arch == amd64
#        run: |
#          sudo .github/workflows/generic-build.sh ${{ matrix.arch }}
#          sudo .github/workflows/ci-run-tests.sh ${{ matrix.arch }}
#
#      - uses: actions/upload-artifact@v2
#        with:
#          name: kcov-${{ matrix.arch }}.tar.gz
#          path: kcov-${{ matrix.arch }}.tar.gz


  build-and-push-docker-image:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Docker Hub login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

    - name: Build docker image
      run: docker build -t kcov/kcov:${{ github.event.release.tag_name }} .

    - name: Push to Docker Hub
      run: docker push kcov/kcov:${{ github.event.release.tag_name }}

  create_release:
    name: Create release
    needs: [build-and-push-docker-image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: kcov-*/kcov-*.tar.gz
          artifactContentType: application/gzip
          token: ${{ secrets.GITHUB_TOKEN }}
